name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: yashx007
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake Animation to Output Branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
